schemaVersion: 2.2.0
metadata:
  name: demo-nodejs-app
components:
  - container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
#      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 16G
      memoryRequest: 8G
      endpoints:
        - name: http-3000
          targetPort: 3000
    name: runtime
commands:
  - id: install
    exec:
      commandLine: npm install
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      commandLine: node app.js
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: run
  - id: install-aws-cli
    exec:
      commandLine: 'pip3 install awscli --upgrade'
      component: runtime
  - id: deploy-on-eks
    exec:
      commandLine: kubectl --kubeconfig kube-files/ekubec -n ude-demo-app apply -f kube-files/ude-demoapp-deploy.yaml
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: false
        kind: run
  - id: deploy-on-aks
    exec:
      commandLine: kubectl --kubeconfig kube-files/akubec -n ude-demo-app apply -f kube-files/ude-demoapp-deploy.yaml
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: false
        kind: run
  - id: deploy-on-gke
    exec:
      commandLine: kubectl --kubeconfig kube-files/gkubec -n ude-demo-app apply -f kube-files/ude-demoapp-deploy.yaml
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: false
        kind: run
events:
  postStart:
    - install-aws-cli
