schemaVersion: 2.2.0
metadata:
  name: demo-nodejs-app
components:
  - container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: http-3000
          targetPort: 3000
    name: runtime
commands:
  - id: install
    exec:
      commandLine: npm install
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      commandLine: node app.js
      component: runtime
      workingDir: ${PROJECT_SOURCE}
      group:
        isDefault: true
        kind: run
  - id: install-aws-cli
    exec:
      commandLine: 'pip3 install awscli --upgrade'
      component: runtime
events:
  postStart:
    - install-aws-cli
