apiVersion: v1
kind: Service
metadata:
  name: njs-service
  labels:
    app: njs-app
spec:
  type: LoadBalancer
  selector:
    app: njs-app
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080