apiVersion: v1
kind: Service
metadata:
  name: njs-service
  labels:
    app: njs-app
spec:
#  type: LoadBalancer
  type: NodePort
  selector:
    app.kubernetes.io/name: njs-app
#    app: njs-app
  ports:
    - protocol: TCP
#      name: http
      port: 8080
      targetPort: 8080
